### ISSUE TITLE
[Bug] Lerna + react hooks

### ISSUE THREAD

**Issue by meesvandongen** [nozzle/react-static#1021]
### Bug

When running using lerna & react hooks, react-static is not able to export. 
Instead, this error is shown: 
`Invariant Violation: Failed exporting HTML for URL / (src\pages\index.tsx): Minified React error #307; visit https://reactjs.org/docs/error-decoder.html?invariant=307`

According to that page, this is the error: `Hooks can only be called inside the body of a function component`

If I manually place the global `node_modules` in the local project folder, the build succeeds.

### Environment

```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
    Memory: 6.84 GB / 15.95 GB
  Binaries:
    Node: 11.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.1
  Dependencies:
    react: 16.8.1
    react-dom: 16.8.1
    react-static: 6.0.18
```

### Steps to Reproduce the problem

1.  `lerna init`
2.  configure lerna for yarn workspaces
3.  copy template to `/packages` & provide package version
4.  run `lerna bootstrap`
5.  run `yarn build`

### Expected Behavior

The build should succeed

### Reproducible Demo

https://github.com/meesvandongen/bug-lerna-reactstatic

**Comment by tannerlinsley** [comment]
This is a bug with react in general when using lerna or linked dependencies. We're working on a workaround that will hopefully fix this.

**Comment by meesvandongen** [comment]
I bypassed this by switching to pnpm instead of yarn+lerna for management.

**Comment by IOIO72** [comment]
Is it really related to lerna? I'm getting a similar error without lerna.

Everything is fine in dev mode - as soon as I build the site, I'm getting the same error.

Here's the output of debug mode:

```
=> Exporting HTML...
  Error: Invariant Violation: Failed exporting HTML for URL 404 (src/pages/404.js): Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

  - react.development.js:88 invariant
    [honma]/[react]/cjs/react.development.js:88:15

  - react.development.js:1436 resolveDispatcher
    [honma]/[react]/cjs/react.development.js:1436:28

  - react.development.js:1461 useState
    [honma]/[react]/cjs/react.development.js:1461:20

  - App.js:198 App
    /Users/tamio/WebstormProjects/honma/dist/webpack:/Users/tamio/WebstormProjec    ts/honma/src/App.js:198:37

  - react-dom-server.node.development.js:2868 processChild
    [honma]/[react-static]/[react-dom]/cjs/react-dom-server.node.development.js:    2868:14

  - react-dom-server.node.development.js:2792 resolve
    [honma]/[react-static]/[react-dom]/cjs/react-dom-server.node.development.js:    2792:5

  - react-dom-server.node.development.js:3172 ReactDOMServerRenderer.render
    [honma]/[react-static]/[react-dom]/cjs/react-dom-server.node.development.js:    3172:22

  - react-dom-server.node.development.js:3131 ReactDOMServerRenderer.read
    [honma]/[react-static]/[react-dom]/cjs/react-dom-server.node.development.js:    3131:29

  - react-dom-server.node.development.js:3598 renderToString
    [honma]/[react-static]/[react-dom]/cjs/react-dom-server.node.development.js:    3598:27

  - exportRoute.js:127 renderToStringAndExtract
    [honma]/[react-static]/src/static/exportRoute.js:127:21

  - exportRoute.js:191 renderToStringAndExtract
    [honma]/[react-static]/src/static/exportRoute.js:191:15

  - runtime.js:62 tryCatch
    [honma]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [honma]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [honma]/[regenerator-runtime]/runtime.js:114:21

  - exportRoute.js:52 asyncGeneratorStep
    [honma]/[react-static]/lib/static/exportRoute.js:52:103

  - exportRoute.js:54 _next
    [honma]/[react-static]/lib/static/exportRoute.js:54:194
```

**Comment by tannerlinsley** [comment]
Another scenario that causes this bug is when there are 2 versions of React being loaded in the same application. Using Hooks will amplify this issue sooner, so you need to make sure you are only relying on a single version of react for your whole app. Try running `yarn why react` to see which/how many versions you have installed.

We released a fix that should force resolve any react imports to the same version (the one resolved from your project root).

**Comment by wagerfield** [comment]
I am still experiencing this issue—has a solution been implemented yet?

I have a _very simple_ Lerna monorepo with 2 packages: `xrc` and `xrc-app`

`xrc` is the package I'm publishing to NPM and `xrc-app` is the docs website/app for `xrc`

`xrc-app` is _private_ and uses `react-static`

https://github.com/wagerfield/xrc

I have purposefully removed `react` and `react-dom` as dependencies from both `xrc` and `xrc-app` to be absolutely sure that the issue I'm experiencing isn't related to multiple versions of `react` being installed.

After running `yarn` from the root of the monorepo to install the dependencies, I then run `yarn why react` and get:

```
yarn why v1.16.0
[1/4] 🤔  Why do we have the module "react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react@16.8.6"
info Reasons this module exists
   - "_project_#xrc-app#react-static" depends on it
   - Hoisted from "_project_#xrc-app#react-static#react"
info Disk size without dependencies: "248KB"
info Disk size with unique dependencies: "564KB"
info Disk size with transitive dependencies: "648KB"
info Number of shared dependencies: 6
```

This clearly shows that I only have _one_ version of `react` installed (16.8.6) which is the result of `react-static` listing it as a dependency.

Since the `xrc-app` lives inside the `packages` dir, it uses the local version of `xrc` rather than the one published to NPM. Therefore, before you can build the React Static site, you _must run_ `yarn bundle` from the root of the monorepo. This will compile the TypeScript in the `xrc` package using Rollup into `cjs` and `esm` bundles in the `xrc` package that `xrc-app` can then import and use.

After running `yarn bundle` you can now run all of the `app:*` related scripts from the monorepo root.

When you run `yarn app:start` from the monorepo root, it will run the `start` script in the `xrc-app` package which in turn calls `react-static start` to start the development server. This works absolutely fine and you will be able to see the WIP site at `localhost:5000`

However, when you run `yarn app:stage` or `yarn app:build` from the monorepo root it will get as far as compiling all the JS bundles, but then it hangs and eventually fails when exporting the HTML.

I then get the error:

```
Invariant Violation: Failed exporting HTML Minified React error #321
```

https://reactjs.org/docs/error-decoder.html?invariant=321

1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

As mentioned above, running `yarn why react` and `yarn why react-dom` from the monorepo root will show that only one version of both `react` and `react-dom` are installed and that they are the _same version_ of `16.8.6`.

Therefore I would assume that I'm not falling foul of point 1 or 3. Furthermore, I'm not using hooks anywhere in my application code.

If it is an issue with React hooks, then perhaps it's coming from React Static?

The strange thing I have found is that if I copy and paste the `xrc-app` package onto my desktop so that it's completely removed from the Lerna monorepo and run `yarn` or `npm install` inside the package so `react-static` et al are installed and `xrc` is pulled from NPM rather than the local monorepo version, then the `build` and `stage` scripts work.

I've been battling with this one all day and could really use some help please :D

Thanks in advance!

**Comment by sw-yx** [comment]
just to be clear - are you running react static 7?
