### ISSUE TITLE
Hot Reloading seems broken

### ISSUE THREAD

**Issue by Reggino** [nozzle/react-static#397]
Hi,

First off thanks for all the great work on react-static. It's awesome.

I noticed hot-reloading seems broken (since this change: https://github.com/nozzle/react-static/commit/135c499637838cc14f30b779b06a812db2aefcee ?) . Both the "basic" and the "typescript" example in the master-branch no longer seem to reload after editing .jsx / .tsx files.

**Comment by pie6k** [comment]
I can confirm I'm not able to use hot-reloading with typescript example too.

Actually - it works with 'root' files like `App.tsx` but not with eg `containers/*.tsx`.

**Comment by Kisaro** [comment]
Same here, when creating a new project on a fresh react-static install using the basic template, HMR seems to be broken. Not completely though like mentioned above, e.g. changes in App.js would still trigger a reload, changes in route-specific components (e.g. Home.js in the basic template) however do not.

I fixed this in my project for now by reverting the changes of 135c499 for the the index.js and App.js files

**Comment by JustFly1984** [comment]
For me HMR broken for CSS modules. After saving a js or css file, I get js updated, but css for a file I was editing gets flushed out.
I still have all the other components styled, but not those which I touched.

**Comment by cthurston** [comment]
Not sure if this is the same issue or a different one. 

When trying to build the redux example I get:

````
=> Copying public directory...
=> [✓] Public directory copied: 1.854ms
=> Building Routes...
=> [✓] Routes Built: 171.077ms
=> Bundling App...
=> [✓] App Bundled: 5963.323ms
=> Exporting Routes...
TypeError: (0 , _reactHotLoader.hot) is not a function
    at Object.<anonymous> (/Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:630:19)
    at Object.<anonymous> (/Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:631:30)
    at __webpack_require__ (/Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:30:30)
    at Object.<anonymous> (/Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:527:12)
    at __webpack_require__ (/Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:30:30)
    at /Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:73:18
    at /Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:11:17
    at webpackUniversalModuleDefinition (/Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:3:20)
    at Object.<anonymous> (/Users/cthurston/IdeaProjects/react-static-redux/dist/static.398447b2.js:1:1)
    at Module._compile (module.js:612:30)
````

And I had to install react-hot-loader manually.

**Comment by tannerlinsley** [comment]
This should be fixed in the latest release.

- Upgraded to latest `react-hot-loader`
- Disabled code-splitting in dev (this was causing some funky issues)

Make double sure that you are running the latest version of React-Static and especially react-hot-loader (via react-static). If you're still experiencing problems, please file a new issue.

**Comment by tannerlinsley** [comment]
ae7fa4a329155efc948966d8234f9bf661cdbd06
68079dfc9cbd70afc125e5c6dadc68a412399a4f

**Comment by Reggino** [comment]
Nice, that seems do to the trick. Thanks!

**Comment by severen** [comment]
@tannerlinsley Have you made sure to follow this [recommendation](https://github.com/gaearon/react-hot-loader#code-splitting)?

If not, hot reloading *with* code-splitting should work, I think.

**Comment by tannerlinsley** [comment]
Yes. Doing so with code splitting would require the user to Mark every
single route level component as hot, which is lame. This is much easier.
