### ISSUE TITLE
Rehydrate fails when using withRouteData

### ISSUE THREAD

**Issue by efarem** [nozzle/react-static#599]
Related to #567. Using version `5.9.1` hitting a route thats using the `withRouteData` HOC with `index.html` on the end fails with error `RouteData or withRouteData couldn't find any props for path: [path]. You are either missing a route.getData function or you are relying on RouteData/withRouteData where you don't need to.`.

### Steps to Reproduce the problem

- `react-static create` (use basic)
- `yarn build`
- `yarn serve`
- Hit `http://localhost:3000/blog/index.html`

### Expected Behavior

Should rehydrate the html.

**Comment by tannerlinsley** [comment]
This is intentional. React-Static is build to work with suffix-less routes using the History api.

**Comment by tannerlinsley** [comment]
It should yes.

**Comment by efarem** [comment]
I realised my original description didn’t explain that this is specifically a problem in a production bundle.

Also the page renders fine if you don’t use ‘withRouteData’ so at the very least there’s a bit of inconsistency, if that’s by design then fair enough but worth noting.

**Comment by tannerlinsley** [comment]
I'll look into this more.

**Comment by WillDonohoe** [comment]
Hey @tannerlinsley, I'm also having this problem. Not only on .html files, but this also seems to be appearing on 404 pages where `withRouteData` is used. We can get around the problem temporarily by hard coding the data in the template, but this is obviously not ideal.

To repro I've taken your basic example and modified slightly:

static.config.js:
```
{
  is404: true,
  component: 'src/containers/404',
  getData: () => ({
    something: 'a string',
  }),
},
```

404.js:
```
import React from 'react'
import { withRouteData } from 'react-static';

const ErrorPage = ({ something }) => (
  <p>{something}</p>
)

export default withRouteData(ErrorPage)
```

Running `npm run build` and `npm run serve`, then navigating to http://localhost:3000/sgsrgsrg will return the same error: 
```
RouteData or withRouteData couldn't find any props for path: sgsrgsrg. You are either missing a route.getData function or you are relying on RouteData/withRouteData where you don't need to.
```

Thanks

**Comment by anjawaldbauer** [comment]
This is definitely a bug, please reopen.

**Comment by gryzzly** [comment]
@tannerlinsley we also have this issue, where in dev mode everything works flawlessly and after the build we are getting `RouteData or withRouteData couldn't find any props for path: sgsrgsrg. You are either missing a route.getData function or you are relying on RouteData/withRouteData where you don't need to.`

In our case the issue is related to paths not matching in `RouteData.js`

**Comment by tannerlinsley** [comment]
Looks like a bug where the `templateIndex` for 404 pages is not set correctly and ends up trying to load a different template on a 404 hit. If that template uses `RouteData` or `withRouteData` in any way, you will get this error. I'm working on a fix right now.

**Comment by tannerlinsley** [comment]
This should be fixed in 6.1.5

**Comment by ashrewdmint** [comment]
I'm on 6.2.0 and I'm not able to use `RouteData` inside of the 404 page.

`Error: React-Static: <RouteData> could not find any data for this route: shouldsee404. If this is a dynamic route, please remove any reliance on RouteData or withRouteData from this routes components`

**Comment by ashrewdmint** [comment]
Yeah, let me figure out how to get this issue from a new project.

**Comment by ashrewdmint** [comment]
1. Run `react-static create` and use the basic template
2. Try to use `withRouteData` in `pages/404.js` OR, create a `404` route whose component is in `src/containers/404.js` and try to access `withRouteData()` from there.

Example route

```
      {
        path: '404',
        component: 'src/containers/404',
        getData: () => ({
          greeting: 'Hello World!'
        })
      }
```

Example component

```
import React from 'react'
import { withRouteData } from 'react-static'

export default withRouteData(({ greeting }) => (
  <div>
    <h1>404 page</h1>
    <p>{greeting}</p>
  </div>
))
```

**Comment by ashrewdmint** [comment]
Looks like `react-static create` doesn't build a site with the latest version of `react-static` (6.2.0 installed). However, if I use the latest version of `react-static` in `package.json` I still get the error.

**Comment by ashrewdmint** [comment]
Please consider reopening this @tannerlinsley, I can't deploy v6 into production until this is fixed, basically.
