### ISSUE TITLE
[beta-16] bug

### ISSUE THREAD

**Issue by JustFly1984** [nozzle/react-static#701]
Error: [BABEL] /drivemoscow/static.config.js: The 'polyfill' option has been removed. The @bab  el/runtime module now skips polyfilling by default. (While processing: "/drivemoscow/node_modu  les/@babel/plugin-transform-runtime/lib/index.js")

installing `react-static@next` globally, 
creating new project with basic template, 
cd into project, 
`npm i -S react-static@next`

```
$ yarn start
yarn run v1.9.4
$ react-static start
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/drivemoscow/node_modules/swimmer/lib/index.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/drivemoscow/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/drivemoscow/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

`yarn add  babel-runtime`

```
$ yarn start
yarn run v1.9.4
$ react-static start
  Error: [BABEL] /Users/justfly/projects/drivemoscow/static.config.js: The 'polyfill' option has been removed. The @bab  el/runtime module now skips polyfilling by default. (While processing: "/Users/justfly/projects/drivemoscow/node_modu  les/@babel/plugin-transform-runtime/lib/index.js")

  - index.js:82 _default
    [drivemoscow]/[@babel]/plugin-transform-runtime/lib/index.js:82:13

  - index.js:19
    [drivemoscow]/[@babel]/helper-plugin-utils/lib/index.js:19:12

  - full.js:157 loadDescriptor
    [drivemoscow]/[@babel]/core/lib/config/full.js:157:14

  - caching.js:32 cachedFunction
    [drivemoscow]/[@babel]/core/lib/config/caching.js:32:19

  - full.js:192 loadPluginDescriptor
    [drivemoscow]/[@babel]/core/lib/config/full.js:192:28

  - full.js:68 config.plugins.map.descriptor
    [drivemoscow]/[@babel]/core/lib/config/full.js:68:16

  - Array.map

  - full.js:67 recurseDescriptors
    [drivemoscow]/[@babel]/core/lib/config/full.js:67:38

  - full.js:86 recurseDescriptors
    [drivemoscow]/[@babel]/core/lib/config/full.js:86:27

  - full.js:100 loadFullConfig
    [drivemoscow]/[@babel]/core/lib/config/full.js:100:6
```

I have no idea what could go wrong

My other project is still runing, but I think it is running only cos I did not reinstall node_modules.

**Comment by JustFly1984** [comment]
This is clearly something wrong with @babel.

The only way I could run npm run successfully is by copying all files in /node_modules/@babel/ from my old project, and merging it to /node_modules/@babel/ in new project. simple replacement causes another error: missing browserlist package.

**Comment by mjsisley** [comment]
I was able to fix this bug by removing the options that no longer exist for `babel-runtime` in the `babel-preset.js` config file (see #700)

**Comment by JustFly1984** [comment]
@tannerlinsley please merge the fix to @next

**Comment by tannerlinsley** [comment]
This should be fixed in master now.

**Comment by JustFly1984** [comment]
Can you please publish this fix to react-static@next ? I can't build to production. Still have same error in beta.16.

**Comment by Hypnosphi** [comment]
You probably need to pin all `@babel/*` dependencies to exact version (without `^`) for now, because they still are in rc and therefore can have breaking changes in each release

**Comment by JustFly1984** [comment]
I still have this issue with beta.16, which stopping me from starting new projects with react-static

**Comment by lexaurin** [comment]
True, fixed in master. Please release new beta version
